# Generated by Django 5.1 on 2025-01-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_clouddriveconnection_drive_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddriveconnection',
            name='access_token',
            field=models.TextField(),
        ),
    ]
