# Generated by Django 5.1.4 on 2025-01-06 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_clouddriveconnection_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clouddriveconnection',
            old_name='google_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='clouddriveconnection',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Drive'), ('dropbox', 'Dropbox')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
