# Generated by Django 5.1.4 on 2025-01-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_google_email_clouddriveconnection_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_service', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_access_token', models.TextField(blank=True, null=True)),
                ('destination_path', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('source_access_token', models.TextField()),
                ('source_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255)),
                ('task_type', models.CharField(choices=[('copy', 'Copy'), ('cut', 'Cut'), ('delete', 'Delete')], max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
