# Generated by Django 5.1.4 on 2025-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_task_status_remove_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='destination_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('copy', 'Copy'), ('cut', 'Cut'), ('delete', 'Delete')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
