# Generated by Django 5.1.4 on 2025-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_task_destination_email_task_status_task_task_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='destination_access_token',
        ),
        migrations.RemoveField(
            model_name='task',
            name='source_access_token',
        ),
        migrations.AddField(
            model_name='task',
            name='destination_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source_account_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
