# Generated by Django 5.1.4 on 2025-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_clouddriveconnection_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddriveconnection',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
